- platform: cisco_iosxe
  host: 192.168.139.1
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10
- platform: cisco_iosxe
  host: 192.168.139.2
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10
- platform: cisco_iosxe
  host: 192.168.139.3
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10
