- platform: cisco_iosxe
  host: 192.168.100.1
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  timeout_socket: 5
  timeout_transport: 10
  transport: asyncssh
- platform: cisco_iosxe
  host: 192.168.100.2
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  timeout_socket: 5
  timeout_transport: 10
  transport: asyncssh
- platform: cisco_iosxe
  host: 192.168.100.3
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  timeout_socket: 5
  timeout_transport: 10
  transport: asyncssh
- device_type: cisco_ios
  host: 192.168.100.1
  username: cisco
  password: cisco
  secret: cisco
  timeout: 10
- device_type: cisco_ios
  host: 192.168.100.2
  username: cisco
  password: cisco
  secret: cisco
  timeout: 10
